### ISSUE TITLE
Allow login information for private repository

### ISSUE THREAD

**Issue by mymasse** [tlwr/registry-tag-resource#1]
Great resource by the way, I saw your post on the concourse discord server and it was posted exactly at the time I was thinking about something like this.

I've started using it for updating some of our images using docker hub source images however some of our other images are stored in our private docker registry hosted on our Nexus repo and we don't allow un-authenticated request. 

Is it possible to update the resource to allow user/password to be specified and used?

**Comment by tlwr** [comment]
Thank you for reading the post!

Different registries have different authentication strategies. The resource type does not currently support any auth mechanisms but I can add them

Do you use HTTP Basic Auth, TLS client certificates, or HTTP headers?

**Comment by mymasse** [comment]
So we use the `registry-image` with our private repo and that works with specifying username/password so must be Basic Auth.

**Comment by mymasse** [comment]
Just checked the code for `registry-image` and it's basic auth, that would be awesome

**Comment by tlwr** [comment]
This is now implemented, a new image has been pushed to

```
ghcr.io/tlwr/registry-tag-resource:ca0bb9df4bb929b94db3a91bab16ac27bb1caac1
```

I haven't tested it other than spec tests, so please let me know how you get on

**Comment by mymasse** [comment]
That works but I have one more question, my repository returns this:
```
{"name":"<OWNER>/<IMAGE>","tags":["2.22.1","2.23.0","latest"]}
```
My resource config uses `regexp: ^\d+\.\d+\.\d+$` but concourse used 2.22.1 as the latest version, why?

**Comment by tlwr** [comment]
Regexp matching on its own just orders them by timestamp, you should specify `semver` in the source configuration:

```
source:
  regexp: '^\d+\.\d+\.\d+$'
  
  semver:
    matcher: '>= 1'
```

(If you're specifying `semver` and you still get this behaviour then it is a bug)

**Comment by mymasse** [comment]
Yeah that works all is good
